name: kfupm_hachthon
publish_to: 'none'
version: 2.3.8+2

environment:
    sdk: '>=2.19.0 <3.0.0'
    flutter: '>=3.7.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_web_plugins:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    intl:
    timezone: 0.9.1

    # ax:
    #     path: ../../packages/ax
    # ax_api:
    #     path: ../../packages/ax_api
    # redux_simple:
    #     path: ../../packages/redux_simple

    # iOS
    cupertino_icons: 1.0.5

    # Networking
    http:

    # Utils
    permission_handler: 10.2.0
    path_provider:
    screenshot: 1.3.0
    go_router:

    # Code
    freezed_annotation:
    json_annotation:

    # Engage
    share_plus: 6.3.0
    in_app_review: 2.0.6

    # UI
    flex_color_picker: 3.0.2
    flutter_slidable: 2.0.0
    responsive_grid: 2.1.0
    decorated_icon: 1.2.1
    home_widget: 0.2.0+1
    demoji: 2.0.0
    flutter_markdown: 0.6.13
    file_picker: 5.2.5
    pdf: 3.8.4
    scrollable_positioned_list: 0.3.5
    persistent_bottom_nav_bar: 5.0.2
    mix: 0.0.7
    emoji_selector: 0.0.5
    flutter_svg: ^2.0.1
    flutter_spinkit: ^5.1.0
    flutter_hooks: ^0.18.5+1
    flutter_keyboard_visibility: ^5.4.0
    google_maps_flutter: ^2.2.3
    supabase_flutter: ^1.4.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints:
    build_runner:
    freezed:
    json_serializable:
    flutter_launcher_icons: 0.11.0
    flutter_native_splash: 2.2.16
    dart_code_metrics:
    dependency_validator:

    # torjoman:
    #     path: ../../packages/torjoman

flutter:
    uses-material-design: true

    fonts:
        - family: KhottaIcons
          fonts:
            

        - family: AxendaIcons
          fonts:
              

        - family: Almarai
          fonts:
           
    assets:
        - assets/
        - assets/roadmap.png
   

flutter_icons:
    ios: true
    android: true
   
    # iOS
    remove_alpha_ios: true
    # Android adaptive icon
    adaptive_icon_background: '#2F3137'
   
    web:
        generate: true
        image_path: 'assets/launcher/icon.png'
        background_color: '#2F3137'
        theme_color: '#2F3137'
    macos:
        generate: true
     

flutter_native_splash:
    # This package generates native code to customize Flutter's default white native splash screen
    # with background color and splash image.
    # Customize the parameters below, and run the following command in the terminal:
    # flutter pub run flutter_native_splash:create
    # To restore Flutter's default white splash screen, run the following command in the terminal:
    # flutter pub run flutter_native_splash:remove

    # color or background_image is the only required parameter.  Use color to set the background
    # of your splash screen to a solid color.  Use background_image to set the background of your
    # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
    # size of the app. Only one parameter can be used, color and background_image cannot both be set.
    color: '#2F3137'
    #background_image: "assets/background.png"

    # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
    # the leading # character.

    # The image parameter allows you to specify an image used in the splash screen.  It must be a
    # png file and should be sized for 4x pixel density.
   

    # The color_dark, background_image_dark, and image_dark are parameters that set the background
    # and image when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above. If the image_dark parameter is specified, color_dark or
    # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
    # set.
    #color_dark: "#042a49"
    #background_image_dark: "assets/dark-background.png"
    #image_dark: assets/splash-invert.png

    # The android, ios and web parameters can be used to disable generating a splash screen on a given
    # platform.
    #android: false
    #ios: false
    #web: false

    # The position of the splash image can be set with android_gravity, ios_content_mode, and
    # web_image_mode parameters.  All default to center.
    #
    # android_gravity can be one of the following Android Gravity (see
    # https://developer.android.com/reference/android/view/Gravity): bottom, center,
    # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
    # fill_vertical, left, right, start, or top.
    #android_gravity: center
    #
    # ios_content_mode can be one of the following iOS UIView.ContentMode (see
    # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
    # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
    # bottomLeft, or bottomRight.
    #ios_content_mode: center
    #
    # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
    #web_image_mode: center

    # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
    # has no notification bar.  Defaults to false.
    # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
    #       To show the notification bar, add the following code to your Flutter app:
    #       WidgetsFlutterBinding.ensureInitialized();
    #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
    #fullscreen: true

    # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
    # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
    # do not remove any spaces:
    #info_plist_files:
    #  - 'ios/Runner/Info-Debug.plist'
    #  - 'ios/Runner/Info-Release.plist'

    # To enable support for Android 12, set the following parameter to true.  Defaults to false.
    #android12: true
